apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: kiratech-test
spec:
  selector: 
    app: jenkins-server
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080