---
- name: configure ec2 instances
  hosts: master, worker
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles: 
    - configure-ec2
