---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "node"
    key_name: kiratech-challenge
    instance_type: t2.medium
    image_id: ami-0d06de6bae4839627
    security_group: default
    network:
      assign_public_ip: true
    wait: yes
    count: 3
    aws_region: eu-central-1
    aws_access_key:  #{{ secrets.AWS_ACCESS_KEY }}
    aws_secret_key:  #{{ secrets.AWS_SECRET_KEY }}
    